language: java

jdk:
  - openjdk17
  
cache:
  directories:
    - $HOME/.gradle
    
script:
  - ./gradlew build generateDocs --refresh-dependencies

env:
  global:
  - ENCRYPTION_LABEL: "189e52c2c347"
  - COMMIT_AUTHOR_EMAIL: "melaasar@gmail.com"

deploy:
  - provider: script
    script: .deploy/deploy.sh
    skip_cleanup: true
    on:
      tags: true
      branch: master
  - provider: script
    script: ./gradlew publish
    skip_cleanup: true
    on:
      tags: true
      branch: master
